<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $book_category = array(
            array('book_id' => '1', 'category_id' => '1'),
            array('book_id' => '2', 'category_id' => '1'),
            array('book_id' => '5', 'category_id' => '1'),
            array('book_id' => '6', 'category_id' => '1'),
            array('book_id' => '7', 'category_id' => '1'),
            array('book_id' => '8', 'category_id' => '1'),
            array('book_id' => '9', 'category_id' => '1'),
            array('book_id' => '10', 'category_id' => '1'),
            array('book_id' => '11', 'category_id' => '1'),
            array('book_id' => '12', 'category_id' => '1'),
            array('book_id' => '29', 'category_id' => '1'),
            array('book_id' => '30', 'category_id' => '1'),
            array('book_id' => '44', 'category_id' => '1'),
            array('book_id' => '45', 'category_id' => '1'),
            array('book_id' => '46', 'category_id' => '1'),
            array('book_id' => '47', 'category_id' => '1'),
            array('book_id' => '48', 'category_id' => '1'),
            array('book_id' => '49', 'category_id' => '1'),
            array('book_id' => '70', 'category_id' => '1'),
            array('book_id' => '3', 'category_id' => '2'),
            array('book_id' => '4', 'category_id' => '2'),
            array('book_id' => '13', 'category_id' => '2'),
            array('book_id' => '14', 'category_id' => '2'),
            array('book_id' => '15', 'category_id' => '2'),
            array('book_id' => '16', 'category_id' => '2'),
            array('book_id' => '17', 'category_id' => '2'),
            array('book_id' => '18', 'category_id' => '2'),
            array('book_id' => '19', 'category_id' => '2'),
            array('book_id' => '20', 'category_id' => '2'),
            array('book_id' => '41', 'category_id' => '2'),
            array('book_id' => '2', 'category_id' => '3'),
            array('book_id' => '3', 'category_id' => '3'),
            array('book_id' => '12', 'category_id' => '3'),
            array('book_id' => '21', 'category_id' => '3'),
            array('book_id' => '22', 'category_id' => '3'),
            array('book_id' => '23', 'category_id' => '3'),
            array('book_id' => '24', 'category_id' => '3'),
            array('book_id' => '25', 'category_id' => '3'),
            array('book_id' => '26', 'category_id' => '3'),
            array('book_id' => '28', 'category_id' => '3'),
            array('book_id' => '29', 'category_id' => '3'),
            array('book_id' => '30', 'category_id' => '3'),
            array('book_id' => '1', 'category_id' => '4'),
            array('book_id' => '2', 'category_id' => '4'),
            array('book_id' => '31', 'category_id' => '4'),
            array('book_id' => '32', 'category_id' => '4'),
            array('book_id' => '33', 'category_id' => '4'),
            array('book_id' => '34', 'category_id' => '4'),
            array('book_id' => '35', 'category_id' => '4'),
            array('book_id' => '36', 'category_id' => '4'),
            array('book_id' => '37', 'category_id' => '4'),
            array('book_id' => '38', 'category_id' => '4'),
            array('book_id' => '39', 'category_id' => '4'),
            array('book_id' => '40', 'category_id' => '4'),
            array('book_id' => '42', 'category_id' => '4'),
            array('book_id' => '43', 'category_id' => '4'),
            array('book_id' => '44', 'category_id' => '4'),
            array('book_id' => '45', 'category_id' => '4'),
            array('book_id' => '46', 'category_id' => '4'),
            array('book_id' => '47', 'category_id' => '4'),
            array('book_id' => '49', 'category_id' => '4'),
            array('book_id' => '1', 'category_id' => '5'),
            array('book_id' => '4', 'category_id' => '5'),
            array('book_id' => '42', 'category_id' => '5'),
            array('book_id' => '43', 'category_id' => '5'),
            array('book_id' => '44', 'category_id' => '5'),
            array('book_id' => '45', 'category_id' => '5'),
            array('book_id' => '46', 'category_id' => '5'),
            array('book_id' => '74', 'category_id' => '5'),
            array('book_id' => '50', 'category_id' => '6'),
            array('book_id' => '51', 'category_id' => '6'),
            array('book_id' => '52', 'category_id' => '6'),
            array('book_id' => '53', 'category_id' => '6'),
            array('book_id' => '54', 'category_id' => '6'),
            array('book_id' => '55', 'category_id' => '6'),
            array('book_id' => '56', 'category_id' => '6'),
            array('book_id' => '57', 'category_id' => '6'),
            array('book_id' => '58', 'category_id' => '6'),
            array('book_id' => '59', 'category_id' => '6'),
            array('book_id' => '60', 'category_id' => '6'),
            array('book_id' => '61', 'category_id' => '7'),
            array('book_id' => '62', 'category_id' => '7'),
            array('book_id' => '63', 'category_id' => '7'),
            array('book_id' => '64', 'category_id' => '7'),
            array('book_id' => '65', 'category_id' => '7'),
            array('book_id' => '66', 'category_id' => '7'),
            array('book_id' => '67', 'category_id' => '7'),
            array('book_id' => '68', 'category_id' => '7'),
            array('book_id' => '69', 'category_id' => '7'),
            array('book_id' => '70', 'category_id' => '8'),
            array('book_id' => '71', 'category_id' => '8'),
            array('book_id' => '72', 'category_id' => '8'),
            array('book_id' => '73', 'category_id' => '8'),
            array('book_id' => '74', 'category_id' => '8'),
            array('book_id' => '75', 'category_id' => '8'),
            array('book_id' => '76', 'category_id' => '8'),
            array('book_id' => '77', 'category_id' => '8'),
            array('book_id' => '78', 'category_id' => '8'),
            array('book_id' => '79', 'category_id' => '8'),
            array('book_id' => '80', 'category_id' => '8'),
            array('book_id' => '81', 'category_id' => '8'),
            array('book_id' => '82', 'category_id' => '8'),
            array('book_id' => '83', 'category_id' => '9'),
            array('book_id' => '84', 'category_id' => '9'),
            array('book_id' => '85', 'category_id' => '9'),
            array('book_id' => '86', 'category_id' => '9'),
            array('book_id' => '87', 'category_id' => '9'),
            array('book_id' => '88', 'category_id' => '9'),
            array('book_id' => '89', 'category_id' => '9'),
            array('book_id' => '90', 'category_id' => '9'),
            array('book_id' => '91', 'category_id' => '9'),
            array('book_id' => '92', 'category_id' => '9'),
            array('book_id' => '93', 'category_id' => '9'),
            array('book_id' => '94', 'category_id' => '9'),
            array('book_id' => '95', 'category_id' => '9'),
            array('book_id' => '96', 'category_id' => '9'),
            array('book_id' => '97', 'category_id' => '9'),
            array('book_id' => '98', 'category_id' => '10'),
            array('book_id' => '99', 'category_id' => '10'),
            array('book_id' => '100', 'category_id' => '10'),
            array('book_id' => '101', 'category_id' => '10'),
            array('book_id' => '102', 'category_id' => '10'),
            array('book_id' => '103', 'category_id' => '10'),
            array('book_id' => '104', 'category_id' => '10'),
            array('book_id' => '105', 'category_id' => '10'),
            array('book_id' => '106', 'category_id' => '10')
        );

        DB::table('book_category')->insert($book_category);
    }
}
